//Film
export const FETCH_FILM = "FETCH_FILM";
export const FETCH_FILM_FOLLOW_DAY = "FETCH_FILM_FOLLOW_DAY";
export const FETCH_BANNER_FILM = "FETCH_BANNER_FILM";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const FETCH_FILM_DETAIL = "FETCH_FILM_DETAIL";
export const FETCH_FILM_SHOWTIME = "FETCH_FILM_SHOWTIME";

//User
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";

//Cinema
export const FETCH_CINEMA_SYSTEM = "FETCH_CINEMA_SYSTEM";
export const FETCH_CINEMA_INFO_IN_SYSTEM = "FETCH_CINEMA_INFO_IN_SYSTEM";
export const FETCH_FILM_FOLLOW_CINEMA = "FETCH_FILM_FOLLOW_CINEMA";
export const SELECTED_ID_CINEMA = "SELECTED_ID_CINEMA";
export const SELECTED_DATE = "SELECTED_DATE";
export const FETCH_TICKET_ROOM = "FETCH_TICKET_ROOM";
export const FETCH_TICKET_ROOM_CHAIR = "FETCH_TICKET_ROOM_CHAIR";
export const SELECT_CHAIR = "SELECT_CHAIR";
